[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/berto/queue"
